---
repository:
  path: github.com/virtualtam/ccache_exporter/v4

go:
  # Whenever the Go version is updated here, go.mod must also be updated.
  version: "1.24"
  cgo: true

build:
  prefix: .
  binaries:
    - name: build/ccache_exporter
      path: ./cmd/ccache_exporter
    - name: build/ccacheparser
      path: ./cmd/ccacheparser
  flags: -a -trimpath
  ldflags: |
    -s
    -X {{repoPath}}/v4/version.Version={{.Version}}
    -X {{repoPath}}/v4/version.Revision={{.Revision}}
    -X {{repoPath}}/v4/version.Branch={{.Branch}}
    -X {{repoPath}}/v4/version.BuildUser={{user}}@{{host}}
    -X {{repoPath}}/v4/version.BuildDate={{date "20060102-15:04:05"}}

crossbuild:
  platforms:
    - darwin/amd64
    - darwin/arm64
    - linux/amd64
    - linux/arm64
    - windows/amd64

tarball:
  prefix: .
  files:
    - CHANGELOG.md
    - LICENSE
    - README.md
