---
version: "3"

networks:
  prometheus:

volumes:
  grafana-data:
  prometheus-data:

services:
  ccache-exporter:
    image: virtualtam/ccache-exporter
    build: .
    networks:
      prometheus:
    ports:
      - 19508:9508
    volumes:
      - ${HOME}/.ccache:/home/exporter/.ccache:ro

  grafana:
    image: grafana/grafana:10.2.4
    depends_on:
      - prometheus
    networks:
      prometheus:
    ports:
      - 13000:3000
    volumes:
      - ./docker/grafana-datasources.yml:/etc/grafana/provisioning/datasources/all.yml
      - ./docker/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./docker/dashboards:/opt/dashboards
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:v1.7.0
    networks:
      prometheus:
    pid: 'host'
    ports:
      - 19100:9100
    cap_add:
      - SYS_TIME
    volumes:
      - "/proc:/host/proc:ro,rslave"
      - "/sys:/host/sys:ro,rslave"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'

  prometheus:
    image: prom/prometheus:v2.49.1
    networks:
      prometheus:
    ports:
      - 19090:9090
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
