{
 "title": "ccache",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache hit ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "ccache_cache_hit_ratio" }
   ]
  },
  {
   "title": "Cache size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "ccache_cache_size_bytes" }
   ]
  },
  {
   "title": "Cache hit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ccache_cache_hit_total)" }
   ]
  },
  {
   "title": "Cache miss",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "ccache_cache_miss_total" }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ccache_cache_hit_total", "legendFormat": "Cache hit ({{mode}})" },
    { "expr": "ccache_cache_miss_total", "legendFormat": "Cache miss" }
   ]
  }
 ]
}