---
name: build-and-test

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          # Whenever the Go version is updated here, .promu.yml should also be updated.
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test
