---
name: build-and-test

on:  # yamllint disable-line rule:truthy
  push:
    branches: []
    tags:
      - v*
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          # Whenever the Go version is updated here, .promu.yml should also be updated.
          - 1.19.x
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: make test
